### ISSUE TITLE
test it elsewhere

### ISSUE THREAD

**Issue by neeasade** [neeasade/myron-themes#1]
I want to test that this works outside of my own setup, and @winny- volunteered 

you'll need to install: https://github.com/neeasade/color-tools.el
and then this repo, and then: 

`(load-theme 'tarp-mcfay t)`

**Comment by winny-** [comment]
Turns out `use-package` does not handle deps when a `:load-path` is used.  I manually installed the deps, but got the following errors:

```
ELISP> (load "tarp-mcfay-theme.el")
*** Eval error ***  Symbol’s value as variable is void: _
ELISP> (load "tarp-marlowe-theme.el")
*** Eval error ***  Wrong type argument: stringp, 4
ELISP> (load "tarp-marlowe-theme.el")
*** Eval error ***  Wrong type argument: stringp, 4
ELISP> (load "tarp-struan-theme.el")
*** Eval error ***  Symbol’s value as variable is void: _
```

I was able to load tarps.el, though.

Tested on `GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)\n of 2020-12-24`

Maybe I did something weirdly?  I could attempt with straight.el?

**Comment by neeasade** [comment]
ope. That is just unfortunate timing, I was changing a function in color-tools.el to have a consistent interface, and for about a 30 minute window things were out of sync. can you pull the latest of both and try again

**Comment by winny-** [comment]
No worries thought i broke things!! =)

Able to load struan but it appears to have set some theme settings on load, instead of load-theme :thinking: 

some stuff from `*messages*`

```
Loading /tmp/ed/.emacs.d/tarps/tarp-struan-theme.el (source)...done
t
Loading /tmp/ed/.emacs.d/tarps/tarp-marlowe-theme.el (source)...
if: Wrong number of arguments: nil, 5
Loading /tmp/ed/.emacs.d/tarps/tarp-mcfay-theme.el (source)...
cl-subseq: Bad bounding indices: -1, nil
```

**Comment by winny-** [comment]
BTW on my testing strategy:

- run emacs like `HOME=/tmp/temphome emacs`
- add MELPA
- manually install the deps with `package-install`
- `add-to-list` the load path
- `load` the .el's

this should do the trick:

```
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/") t)
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize)
(package-refresh-contents)  ;; might be unnecessary

(add-to-list 'load-path "~/.emacs.d/tarps")
(add-to-list 'load-path "~/.emacs.d/color-tools.el")

(set-variable 'package-selected-packages '(base16-theme fn ht helpful dash hsluv))
(package-install-selected-packages)


(load "tarps.el")
(load "color-tools.el")
(load "tarp-mcfay-theme.el")
```

**Comment by neeasade** [comment]
noting from irc convo the emacs version was 26.3, whereas my testing is 27.1n

> if: Wrong number of arguments: nil, 5

def a little weird...

```
(load "tarps.el")
(load "color-tools.el")
(load "tarp-mcfay-theme.el")
```

ah -- this part should be:

```
(load "tarps.el")
(load-theme 'tarp-mcfay t)
```
Thanks for posting the code, I'll test that

**Comment by neeasade** [comment]
All themes working now (tested on emacs 27.1) -- code below:

setup: 

```
mkdir /tmp/temphome
git clone "https://github.com/neeasade/tarps" /tmp/temphome
git clone "https://github.com/neeasade/color-tools" /tmp/temphome
HOME=/tmp/temphome emacs
```

Then, in scratch (mx eval buffer):

```
(require 'package)
(add-to-list 'package-archives
  '("melpa" . "http://melpa.org/packages/") t)
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize)
(package-refresh-contents)  ;; might be unnecessary

(add-to-list 'load-path "~/color-tools.el")
(add-to-list 'load-path "~/tarps")

(set-variable 'package-selected-packages '(base16-theme fn ht helpful dash hsluv))
(package-install-selected-packages)

(require 'tarps)
(load-theme 'tarp-mcfay t)
``` 

thanks @winny- <3
